config/routes.rb
Rails.application.routes.draw do

  resources :food_trucks do
    resources :reviews, only: [:create, :update, :index]
  end
  resources :users 

  get "/users/:id", to: "users#show"
  get "/food_truck_reviews", to: "reviews#index"
  get "/login", to: "sessions#login", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#logout", as: "logout"
  get "/auth/google_oauth2/callback", to: "sessions#google_omniauth"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_truck.rb
class FoodTruck < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
    scope :kind_of_food, -> (kind_of_food){ where("kind_of_food LIKE ?", "%#{kind_of_food}%") }
    scope :search, -> (name){where("name LIKE ?", "%#{name}%")}
   
    scope :filter_by_params, ->(params){
    search(params[:search])
    .kind_of_food(params[:kind_of_food])
  }
 


end 

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :food_truck
  validates :content, length: { minimum: 5}
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reviews
    has_many :food_trucks, through: :reviews
    validates :username, :email, uniqueness: true
    validates :username, :email, presence: true

   
    def self.find_or_create_from_google(user_info)
        find_or_create_by(email: user_info[:email]) do |user|
          user.username = user_info[:name] 
          user.password = SecureRandom.hex
        end
      end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    #helper methods are available in all of your controllers and views.
    helper_method :current_user, :logged_in?
    def current_user
        if session[:user_id]
        User.find(session[:user_id])
        end
    end

    def logged_in?
        !!current_user
    end
  
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController

    def index
        @params = params.permit(:kind_of_food, :search).to_h
        if @params
            @food_trucks = FoodTruck.search(@params[:search])
        else
            @food_trucks = FoodTruck.all
        end
    end

    def show
        @food_truck = FoodTruck.find(params[:id])
        @review = Review.find_or_initialize_by(user: current_user, food_truck: @food_truck)
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_food_truck
    before_action :set_review, only: [:update]

    def index
       if @food_truck
           @reviews = @food_truck.reviews
       else
        @reviews = current_user.reviews
       end
    end


    def create
        @review = current_user.reviews.build(review_params)
        @review.food_truck = @food_truck
        if @review.save
          redirect_to @food_truck
        else
          render :"food_trucks/show"
        end
      end

    def update
      if @review.update(review_params)
        redirect_to @food_truck
      else 
        render :"food_trucks/show"
      end
    end

private

    def set_review
        @review = Review.find(params[:id])
    end

    def set_food_truck
        @food_truck = FoodTruck.find(params[:food_truck_id]) if params[:food_truck_id]
    end

    def review_params
        params.require(:review).permit(:title, :content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create 
        user = User.find_by_username(params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to food_trucks_path
        else
            flash[:errors] = ["Invalid username or password."]
            redirect_to login_path
        end
    end

    def logout
        session.clear
        redirect_to new_user_path
    end

    def google_omniauth
        user_info = request.env['omniauth.auth']['info']
        user = User.find_or_create_from_google(user_info)
        if user
            session[:user_id] = user.id
            redirect_to user
          else
            flash[:errors] = user.errors.full_messages
            redirect_to login_path
        end
    end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to food_trucks_path
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)

    end





end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def human_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end
end

app/helpers/food_trucks_helper.rb
module FoodTrucksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

end
    

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food_trucks/index.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h1>STREET EATS</h1>
    <p>All your favorite food trucks in Knoxville, TN</p>
  </div>
</div>

 <div class="search-bar">
<%= form_tag food_trucks_path, method: :get do %> 
  <%= text_field_tag :search, @params[:search], placeholder: "Captain Muchachos"%> 
  <div class ="button"> <%= submit_tag "Search!" %>
<% end  %>
</div>
</div>
<br>
<br>

<div class="cards">
  <% @food_trucks.each do |food_truck| %>
   <div class="card">
    <%= link_to(image_tag(food_truck.image_url), food_truck) %><br>
      <h3><%= link_to(food_truck.name, food_truck, class: "link-primary") %></h3><br>
 </div>
    <% end %>

app/views/food_trucks/show.html.erb
<div class="hero-image">
  <div class="hero-text">
  <h1> <%= @food_truck.name %></h1>
  </div>
  </div>
<br>
<br>
<br>
<div class="review">
<div class="show">
<%= image_tag @food_truck.image_url %><br>
<h3>Schedule: <%= link_to @food_truck.name,  @food_truck.schedule, class: "link-primary" %></h3><br>
  </div>
</div>
<br>

<div class="details-container">
  <div class="details-content">
    Cuisine <br>
     <%= @food_truck.kind_of_food %>
    </div>
  <div class="details-content">
    Gluten Free<br>
     <%= human_boolean(@food_truck.gluten_free) %>
</div>


<div class="details-content">
    Vegetarian <br>
    <%= human_boolean(@food_truck.vegetarian) %>
    </div>
    </div>
<br>
<br>
<br>
<h1>Leave a Review</h1>
<br>
<div class="review-cards">
  <div class="review-cards-content">
<%= form_for [@food_truck, @review] do |f| %>
  <%= render partial: "layouts/errors", locals: {record: @review} %>  
   <%= f.label "Title" %><br>
   <%= f.text_area :title %><br>
   <%= f.label "Review" %><br>
  <%= f.text_area :content %>
  <%= f.submit  %>
<% end %>
</div>
</div>
<br>
<br>
<br>
<h1> All Reviews</h1>
<br>
<div class="cards">
  <% @food_truck.reviews.each do |review|%>
  <div class="review">
   <h3><%= review.user.username %><br></h3><br>
   <div class="text">
   <%= review.content %><br>
   </div>
   </div>
    <% end %>
</div>
<br>
<br>

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
    <ul class="errors"><% record.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
<% end %>

app/views/layouts/_nav.html.erb
<nav>

  <% if logged_in? %>
    <%= link_to "All Food Trucks", food_trucks_path, class: "link-primary" %> |
    <%= link_to "My Reviews", food_truck_reviews_path(current_user), class: "link-primary" %> |
    <%= link_to "My Profile", user_path(current_user), class: "link-primary" %> |
    <%= link_to "Logout", logout_path, method: "delete", class: "link-primary" %>

  <% else %>
    <%= link_to "All Food Trucks", food_trucks_path, class: "link-primary" %> |
    <%= link_to "Log in with Google", "/auth/google_oauth2", class: "link-primary" %> |
    <%= link_to "Log in", login_path, class: "link-primary"%> |
    <%= link_to "Sign up", new_user_path, class: "link-primary" %> |
  
<% end %>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Street Eats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Spartan:wght@500&display=swap" rel="stylesheet">
    <link rel='icon' href='../../assets/stylesheets/favicon.png' type='image/x-icon'/ >
    
  </head>

  <body>
  <%= render "layouts/nav" %>

    <%= yield %>
  </body>

  <div class="footer">
    <div class="footer-content">
  <p> Street Eats© 2021 </p>
  </div>
  </div>
</html>

app/views/reviews/index.html.erb
<div class="hero-image">
  <div class="hero-text">

<h1>Your Reviews</h1>

</div>
</div>


<% @reviews.each do |review| %>
        <p><%= link_to review.food_truck.name, food_truck_path(review.food_truck) %></p>
        <p><%= review.content %></p>
    
<% end %>

app/views/users/new.html.erb
<h1>Hello!</h1>

<%= form_for @user do |f| %>
    <%= render partial: "layouts/errors", locals: {record: @user} %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign Up!" %>
<%end %>

app/views/users/show.html.erb
<div class="hero-image">
  <div class="hero-text">

<h1>Your Profile</h1>

</div>
</div>

<p>Username: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>